const aiPrompts = [
    // IAC / TERRAFORM / BICEP
    { title: "Terraform Module Construction", text: '"Generate a reusable Terraform module for an AWS VPC with public/private subnets, NAT gateways, and automated tagging rules."', example: 'e.g., "Create a TF module for a secure 3-tier AWS VPC..."' },
    { title: "Terraform State Recovery", text: '"A developer manually deleted an S3 bucket managed by Terraform. Provide a step-by-step guide to recover the state using terraform rm and terraform import."', example: 'e.g., "How do I fix a corrupted TF state when the cloud resource is gone?"' },
    { title: "Bicep Migration Analysis", text: '"List the specific enterprise pros and cons of migrating from Terraform to Azure Bicep for a purely Azure-native organization."', example: 'e.g., "Give me an architectural comparison between Bicep and Terraform."' },
    { title: "Infrastructure Generation", text: '"Generate a Terraform module for [resource] on [cloud provider] with: Remote state backend, Variable-driven configuration, and output the resource ID. Follow naming convention: {env}-{project}-{resource}"', example: 'e.g., "Generate an Azure Resource Group and VNet Terraform config..."' },
    { title: "Terraform Drift Detection", text: '"Write a Bash or Python script that runs `terraform plan` across 5 different environments and alerts Slack if any infrastructure drift is detected."', example: 'e.g., "Create a script to catch manual click-ops changes over the weekend."' },

    // KUBERNETES & DOCKER
    { title: "K8s OOMKill Debugging", text: '"Help me debug a container repeatedly failing with OOMKilled in Kubernetes. Provide kubectl commands to check memory limits, actual usage, and explain how to configure a heap dump."', example: 'e.g., "My Node.js pod keeps crashing with Exit Code 137 in EKS. Walk me through debugging."' },
    { title: "K8s Hardened RBAC", text: '"Generate a Kubernetes RBAC configuration (Role and RoleBinding) that strictly allows a user or service account to only view pods and read logs in a specific namespace."', example: 'e.g., "Create a READ-ONLY RBAC policy for namespace: frontend-prod."' },
    { title: "Docker Multi-Stage Optimize", text: '"Analyze this Dockerfile and rewrite it as a multi-stage build to minimize the final image size and absolutely remove critical security vulnerabilities."', example: 'e.g., "Rewrite this heavy FROM python:3.9-bullseye Dockerfile using alpine."' },
    { title: "Helm Chart Debugging", text: '"My Helm deployment failed with invalid type for value. Provide a strategy to debug Helm template rendering errors using helm template, debug flags, and dry-run."', example: 'e.g., "Helm install fails with YAML parse error on line 42. How do I trace it?"' },
    { title: "K8s Ingress Controller setup", text: '"Design an NGINX Ingress controller configuration for a microservices app running on EKS. Include TLS termination, rate limiting, and path-based routing rules."', example: 'e.g., "Write an ingress.yaml routing /api to backend-svc and / to frontend-svc."' },
    { title: "Karpenter vs Cluster Autoscaler", text: '"Compare AWS Karpenter with the default Kubernetes Cluster Autoscaler for EKS. Give 3 scenarios where Karpenter drastically outperforms CA out of the box."', example: 'e.g., "Give me a migration strategy to move from CA to Karpenter."' },
    { title: "K8s StatefulSet Configuration", text: '"Explain the best practices for deploying a highly resilient PostgreSQL StatefulSet in Kubernetes. Cover PersistentVolumes, anti-affinity rules, and headless services."', example: 'e.g., "Give me the essential architecture considerations for PgSQL in K8s."' },
    { title: "Kubernetes Troubleshooting", text: '"My Kubernetes cluster has the following issue: [describe]. Cluster: [EKS/AKS/Kind]. Version: [version]. Error: [paste error]. Provide a step-by-step debugging approach with kubectl commands."', example: 'e.g., "My Kubernetes cluster has the following issue: Nginx pods stuck in CrashLoopBackOff. Cluster: EKS. Version: 1.28. Error: OOMKilled..."' },
    { title: "Helm Chart Creation", text: '"Generate a production-ready Helm chart for a [Language] microservice. Include standard resources: Deployment, Service, HPA, and Ingress. Make replicas and limits configurable in values.yaml."', example: 'e.g., "Generate a Helm chart for a Python FastAPI microservice..."' },

    // CI/CD & PIPELINES
    { title: "GitHub Actions Matrix Tests", text: '"Write a GitHub Actions workflow that uses a strategy matrix to test a Node/Python app against 3 different OS environments and 3 different language versions in parallel."', example: 'e.g., "Write a GHA workflow testing Python 3.9, 3.10, 3.11 on Ubuntu, Windows, and MacOS."' },
    { title: "Jenkins Shared Libraries", text: '"Refactor this Jenkinsfile Declarative Pipeline to use shared libraries for the build and deploy stages to radically reduce code duplication."', example: 'e.g., "Convert this 200-line Jenkinsfile into a modular shared-library driven pipeline."' },
    { title: "GitLab CI Aggressive Caching", text: '"Provide an optimized GitLab CI .gitlab-ci.yml for a Dockerized project that aggressively caches intermediate layers and node_modules to slash build times."', example: 'e.g., "My GitLab CI build takes 15 mins. Add Docker layer caching."' },
    { title: "ArgoCD GitOps Migration", text: '"Create a migration plan for moving from Jenkins push-based deployments to an ArgoCD pull-based GitOps deployment model for our Kubernetes clusters."', example: 'e.g., "We use Jenkins for Helm upgrades. How do we transition this to ArgoCD safely?"' },
    { title: "Blue/Green Zero-Downtime", text: '"Give me the step-by-step logic and K8s Service/Deployment YAML modifications required to execute a zero-downtime Blue/Green deployment natively without Istio."', example: 'e.g., "Show me how to flip traffic from Blue to Green using simple K8s Service selector updates."' },
    { title: "Pipeline Design Architecture", text: '"Design a CI/CD pipeline for: Language: [Python/Node/Go], Deployment target: [K8s/ECS], Requirements: lint -> test -> build -> security scan -> deploy. Include the pipeline-as-code file."', example: 'e.g., "Design a CI/CD pipeline for: Language: Node.js, Deployment target: AKS..."' },
    { title: "CI/CD Performance Tuning", text: '"Our CI/CD pipeline heavily delayed. Here is the structure: [describe]. Give me 5 advanced optimization strategies (caching, parallelization, multi-stage builds) to drastically reduce build time."', example: 'e.g., "Our GitHub Actions pipeline takes 45 minutes to build a heavy React application..."' },

    // SCRIPTING & AUTOMATION
    { title: "Bash Defensive Hardening", text: '"Rewrite this bash script to be enterprise-grade. Add set -euo pipefail, trap statements for cleanup on failure, logging functions, and parameter validation."', example: 'e.g., "Harden this script: cd /tmp && rm -rf logs && docker restart my-app"' },
    { title: "Python Boto3 Garbage Collection", text: '"Write a resilient Python script using Boto3 to identify unattached EBS volumes across all regions globally and delete them if older than 30 days."', example: 'e.g., "Write a Boto3 script with pagination to delete unused EBS volumes globally."' },
    { title: "Python Boto3 IAM Audit", text: '"Write a Boto3 Python script that lists all AWS IAM Users who have static access keys older than 90 days, and generates a CSV report."', example: 'e.g., "Create an AWS compliance script for IAM key rotation."' },
    { title: "Golang Kubernetes CLI Tool", text: '"Act as a Senior Go Developer. Write a lightweight CLI tool in Go using the `client-go` framework that interacts with K8s to find all failing pods in a namespace."', example: 'e.g., "Write a Go CLI that takes a namespace and outputs pods with > 5 restarts."' },

    // OBSERVABILITY & SRE
    { title: "PromQL Advanced Queries", text: '"Write a PromQL query that calculates the 99th percentile request latency over the last 5 minutes, but only for requests hitting the /checkout endpoint that returned HTTP 500s."', example: 'e.g., "Give me a PromQL query for p99 latency filtering by status=5xx and path=/api/pay."' },
    { title: "Grafana Golden Signals", text: '"Provide a Grafana Dashboard JSON model for a standard Golden Signals dashboard (Latency, Traffic, Errors, Saturation) for an NGINX ingress controller."', example: 'e.g., "Dump a cleanly formatted Grafana JSON dashboard tracking NGINX metrics."' },
    { title: "Logstash Custom Grok Parse", text: '"My Logstash instance is dropping logs due to grok parse failures. Write a custom Grok pattern to perfectly parse this specific custom proprietary application log line."', example: 'e.g., "Write a Grok pattern for: [2026-08-18 20:15] ERROR (Thread-5) UserID=123: DB Timeout"' },
    { title: "Datadog Alert Fatigue Tuning", text: '"Our on-call team is experiencing massive alert fatigue. Give me a strategic framework for configuring Datadog composite monitors to reduce false positives."', example: 'e.g., "How do I tune CPU alerts so they only page when it genuinely impacts end-user latency?"' },
    { title: "Incident Post-Mortem Structure", text: '"Write a blameless incident post-mortem for a production outage caused by [issue]. Follow Google SRE practices. Include sections for: Leadup, Fault, Impact, Detection, Response, and Action Items."', example: 'e.g., "Write a post-mortem for an outage caused by an expired TLS certificate on the main ingress..."' },
    { title: "SRE Strict SLO Definition", text: '"Define strict Service Level Indicators (SLIs) and Service Level Objectives (SLOs) for a user-facing REST API. Give concrete metrics for latency, error rate, and throughput over a 30-day window."', example: 'e.g., "Define SLOs for an API where 99.9% of requests must return within 200ms..."' },

    // ARCHITECTURE & SECURITY
    { title: "Zero-Trust AWS/Azure Pattern", text: '"Design a Zero-Trust architecture diagram flow for a 3-tier application in AWS/Azure. Describe where WAF, PrivateLink, default-deny Security Groups, and mTLS should exist."', example: 'e.g., "Explain how to secure a React -> Node API -> PostgreSQL stack using Zero-Trust."' },
    { title: "DevSecOps Pipeline Checkov", text: '"Integrate Trivy, SonarQube, and Checkov into a standard CI/CD pipeline. Provide the YAML snippets and explain how to fail the build only on CRITICAL CVEs without blocking developers."', example: 'e.g., "Write the GitHub Actions steps to run Checkov on my TF files and Trivy on my Docker image."' },
    { title: "Kubernetes Secret Management", text: '"Compare integrating HashiCorp Vault vs native AWS Secrets Manager / Azure Key Vault into a Kubernetes environment using the External Secrets Operator."', example: 'e.g., "Walk me through syncing an Azure Key Vault secret natively into a K8s Secret using ESO."' },
    { title: "Architecture Expert Review", text: '"Review this DevOps architecture: [paste/describe]. Evaluate against: Reliability (HA, DR), Security (zero-trust), Cost optimization, Scalability, and Operational complexity. Provide specific improvements."', example: 'e.g., "Review this architecture: AWS API Gateway routing to Lambda functions with DynamoDB backup..."' },
    { title: "Security Docker Auditing", text: '"Act as a DevSecOps engineer. Review this Dockerfile for security vulnerabilities, unnecessary packages, and container best practices: [paste Dockerfile]. Provide a hardened version."', example: 'e.g., "Review this Dockerfile: FROM node:18, USER root, RUN npm install..."' },
    { title: "FinOps Cost Optimization", text: '"Analyze this AWS/Azure architecture and identify the top 3 ways to reduce monthly cloud costs without sacrificing high availability: [describe architecture]."', example: 'e.g., "Analyze this AWS architecture containing 3 NAT Gateways and heavily over-provisioned RDS instances..."' },
    { title: "Zero-Downtime DB Migration", text: '"Design a zero-downtime database migration strategy from [Old System] to [New System]. Include rollout phases, backward compatibility plan, rollback triggers, and data consistency checks."', example: 'e.g., "Design a zero-downtime migration strategy from PostgreSQL 12 to PostgreSQL 15..."' },

    // SYSTEM ADMIN / LINUX / NETWORKING
    { title: "Linux Uninterrupted Sleep (D-state)", text: '"A Linux server has inexplicably high load average but incredibly low CPU usage. Walk me through using strace, iotop, and vmstat to diagnose exact disk/network bottlenecks."', example: 'e.g., "Server load is 40.0 but CPU is 10%. How do I find the process stuck in uninterruptible sleep (D state)?"' },
    { title: "Networking Advanced TCP Dump", text: '"Show me the exact `tcpdump` commands to capture dropped packets on port 443 between two specific internal IP subnets. Explain how to read the resulting pcap output."', example: 'e.g., "Give me a tcpdump filter to catch connection resets (RST) on port 443."' },
    { title: "Systemd Service Hardening", text: '"Write a hardened systemd .service file for a massive Go API application. Include auto-restart, standard output logging to journald, and tight CPU/Memory constraints."', example: 'e.g., "Create a systemd file that runs /opt/app/binary as user API and strictly limits it to 2GB RAM."' },
    { title: "Iptables IP Blocking", text: '"We are undergoing a minor DDoS attack from a block of IPs. Provide the exact iptables commands to drop all traffic from a specific CIDR block on port 80/443."', example: 'e.g., "How do I block 192.168.50.0/24 from hitting port 443 using iptables?"' },
    { title: "DNS Dig & Nslookup Trace", text: '"Walk me through exactly what occurs behind the scenes when I execute `dig +trace google.com`. Break down the hierarchy of root servers, TLD servers, and authoritative nameservers."', example: 'e.g., "Teach me how to read the output of a DNS trace to diagnose a stale CNAME record."' },

    // INTERVIEW PREP MODES
    { title: "Behavioral Interview Prep", text: '"Act as a strict engineering manager making a final hiring decision. Ask me a tough behavioral interview question about a time a deployment totally broke production. Wait for my answer, then strictly critique it using the STAR method."', example: 'e.g., "Ask me a behavioral question and wait for my response."' },
    { title: "System Design Interactivity", text: '"Give me a system design interview question for designing a globally distributed logging architecture for 10 million DAU. Let\'s play interactively: I will provide the high-level components first, then critique my design."', example: 'e.g., "Give me an interactive design question for a massive logging ingestion layer..."' }
];

const interviewQuestions = [
    // BEHAVIORAL STAR
    "Behavioral (STAR): Tell me about a time you broke production. What was the absolute catastrophic impact, and exactly how did you fix it and prevent it from happening again?",
    "Behavioral (STAR): Describe a situation where you had a major disagreement with a lead developer regarding CI/CD restrictions or security policies. How did you resolve the technical conflict?",
    "Behavioral (STAR): Tell me about the most complex automation script or IaC module you have written. Why was it complex, what edge cases did you hit, and what value did it bring?",
    "Behavioral (STAR): Give an exact example of a time you had to learn a completely new cloud technology over the weekend to solve a critical business problem on Monday.",
    "Behavioral (STAR): Describe a time when a project deadline was impossibly tight. How did you prioritize your DevOps engineering tasks (cutting scope vs working harder) to ensure delivery?",
    "Behavioral (STAR): Tell me about a time you identified a massive security vulnerability or cloud cost-leak in your infrastructure that nobody else noticed. How did you report it?",
    "Behavioral (STAR): How do you handle it when an application team blames the 'infrastructure' or 'network' for their code crashing, but you know your infrastructure is 100% healthy?",
    "Behavioral (STAR): Let's say you join a company with zero DevOps culture. Everything is manual. How do you convince an old-school SysAdmin team to adopt Terraform and CI/CD?",
    "Behavioral (STAR): Tell me about a time you mentored a junior engineer who was struggling to grasp container orchestration. How did you break it down for them?",
    "Behavioral (STAR): Describe a situation where an incident response post-mortem became toxic or blame-heavy. How did you steer it back to blameless culture?",

    // SCENARIOS & TROUBLESHOOTING
    "Scenario: ALERT! Production Database CPU is at 100% and checkout API is failing. You are the only one on call. Walk me through your first 5 minutes of incident response.",
    "Scenario: A newly deployed microservice is running perfectly in DEV, QA, and UAT, but instantly goes into CrashLoopBackOff in Production. What are the top 3 things you check?",
    "Scenario: Your Kubernetes cluster is completely out of IP addresses globally (IP Exhaustion). You cannot schedule any new pods. How do you recover the massive system?",
    "Scenario: The GitHub Actions CI/CD pipeline that normally takes 5 minutes suddenly takes 45 minutes on everyone's Pull Requests. Where do you start debugging?",
    "Scenario: You inherit legacy AWS/Azure infrastructure built by a vendor entirely by hand (ClickOps). They left zero documentation. How do you map it and bring it under strict IaC?",
    "Scenario: A Junior Developer accidentally committed a highly sensitive AWS Root Access Key to a public GitHub repository exactly 5 minutes ago. What is your exact response sequence?",
    "Scenario: You deleted a critical Kubernetes Namespace by accident in production. Literally everything in it is terminating. You have 30 seconds. Can you stop it? What do you do?",
    "Scenario: Your application relies on an external 3rd-party API that just went completely offline, bringing your whole application down. How would you have architected this differently?",
    "Scenario: Users are reporting random 502 Bad Gateway errors on your web app. It happens approximately 1 out of every 10 page loads. How do you trace this ghost issue?",
    "Scenario: The company wants to migrate 50 monolithic VMs into Kubernetes Docker containers. What is your strategy for breaking down the monoliths safely?",

    // TECHNICAL EXPLANATION
    "Technical Explanation: Explain the difference between Docker `COPY` and `ADD`. When must you absolutely use one over the other in a production image?",
    "Technical Explanation: Describe exactly what happens in a Kubernetes cluster under the hood (API Server, ETCD, Scheduler, Kubelet) when you execute `kubectl apply -f deployment.yaml`.",
    "Technical Explanation: Explain the fundamental difference between an Application Load Balancer (OSI L7) and a Network Load Balancer (OSI L4). Give a specific use-case for each.",
    "Technical Explanation: What is Terraform State? Why is it intensely dangerous to edit manually, and how does Remote Locking prevent disaster?",
    "Technical Explanation: Explain how a Service Mesh (like Istio or Linkerd) actually intercepts container traffic. What is the sidecar proxy pattern and why is it used?",
    "Technical Explanation: What is exactly the difference between Prometheus (Pull-based architecture) and Datadog/NewRelic (Push-based architecture) monitoring architectures?",
    "Technical Explanation: Explain the distinct differences between a K8s Deployment, a StatefulSet, and a DaemonSet. Give a real-world enterprise example for each.",
    "Technical Explanation: Walk me through a DNS resolution. What happens from the precise moment I type google.com to the moment the website IP is fundamentally returned to my browser?",
    "Technical Explanation: How does an Ingress Controller route traffic from the raw public internet to a specific container IP residing inside a completely private subnet?",
    "Technical Explanation: Define 'Zero Trust Network Architecture'. How does it practically differ from a traditional VPN-bastian-host moat-and-castle architecture?"
];
